Added docker-compose documentation
ajacobson/chiadog-docker pull request #7
Opened 2021-05-11 01:18 UTC by noeRls

#6 

Added docker-compose example file in repository.
Updated the README giving the instruction to use docker-compose.

I also included `sh` notation for code block.

2021-05-13 13:10 UTC, Yooooomi requested changes

2021-05-13 13:10 UTC, Yooooomi commented on README.md
> +Ensure that the directory monted for `/root/.chiadog` include a `config.yaml`.
Few typos here, mouNted and includeS

2021-05-13 14:37 UTC, noeRls commented on README.md
> +Ensure that the directory monted for `/root/.chiadog` include a `config.yaml`.
Thanks for checking it, I fixed it !

2021-05-17 20:38 UTC, merged

2021-05-17 20:38 UTC, ajacobson commented
Thanks!